#pragma once

#include "resource.h"
#include "WinApiWrap.h"

#define WIDTH 640
#define HEIGHT 480
#define MAX_RADIOBUTTONS 20
#define IDC_FIGURERADIOBUTTONGROUP (8801 + MAX_RADIOBUTTONS + 1)
#define IDC_COLORRADIOBUTTONGROUP (IDC_FIGURERADIOBUTTONGROUP + MAX_RADIOBUTTONS + 1)
#define IDC_DRAWCHECKBOX (IDC_COLORRADIOBUTTONGROUP + 1)
